name = "After"

[programs]
    # Some daemon that crashes after its running.
    [programs.failing_daemon]
    command = "sleep 5 && exit 1"
    startsecs = 3
    autorestart = true  # Restart in case of failure
    startretries = -1  # Restart indefinitely

    # Should be started only once after daemon is running.
    [programs.ls]
    command = "ls"
    after = "failing_daemon"
