name = "Main"

[programs]

    [programs.ls]
    command = "ls"
    priority = 1
    oneshot = true

    [programs.sleep]
    command = "sleep 3 && false"
    startsecs = 1
    autorestart = true
    startretries = 2